# Logger section
logger:
  level: debug  # Minimum enabled logging level

# Wallet settings
wallet:
  path: /wallet.json  # Path to NEP-6 NEO wallet file
  password: one  # Account password in the wallet

# Profiler section
pprof:
  enabled: true
  address: :6060  # Endpoint for application pprof profiling; disabled by default
  shutdown_timeout: 30s  # Timeout for profiling HTTP server graceful shutdown

# Application metrics section
prometheus:
  enabled: true
  address: :9090  # Endpoint for application prometheus metrics; disabled by default
  shutdown_timeout: 30s  # Timeout for metrics HTTP server graceful shutdown

# Neo main chain RPC settings
mainnet:
  enabled: true # Enable connection to mainchain; by default, 'false', run application in single chain environment
  endpoints: # List of websocket RPC endpoints in mainchain; ignore if mainchain is disabled
    - ws://main-chain:30333/ws

# NeoFS chain RPC settings
fschain:
  consensus:
    magic: 15405
    committee:
      - 0345eefc50545e83dfc7ec9ab648210dddbeb3996912a8ff6416e2d3ec51a8e324
      - 039a1c33ed18bb57f6e6b3e712b54b924d2b9137c4906cf433ee8693a3810e380e
      - 02d3088931c034a390c5bea16d19ef2debe9702019270c94913528a8ac30e17373
      - 02fb7531661401222dcf2711bbd78597e8152ba886612e44ea530a08bbe4eba810
    storage:
      type: boltdb
      path: /neofs_chain/db.bolt
    time_per_block: 1s
    max_traceable_blocks: 200000
    seed_nodes:
      - ir01
      - ir02
      - ir03
      - ir04
    rpc:
      listen:
        - ":30333"
    p2p:
      listen:
        - ":20333"
    set_roles_in_genesis: true

# Network time settings
timers:
  collect_basic_income:
    mul: 1  # Multiplier in x/y relation of when to start basic income asset collection within the epoch
    div: 2  # Divider in x/y relation of when to start basic income asset collecting within the epoch

# Storage node GAS emission settings
emit:
  storage:
    amount: 1000000000  # Fixed8 value of sidechain GAS emitted to all storage nodes once per GAS emission cycle; disabled by default

# Settlement settings
settlement:
  basic_income_rate: 100000000  # Optional: override basic income rate value from network config; applied only in debug mode

experimental:
  allow_ec: true # Optional: allows creating containers with EC placement policies
  chain_meta_data: # Optional: allows creating containers with metadata handled via FS chain
    enabled: true
    seed_port: 20334 # List of existing nodes to communicate with over Neo P2P protocol (addresses are taken from fschain.consensus.seed_nodes, but ports are changed to this value)
    p2p_port: 20334 # Port for network addresses to listen Neo P2P on (addresses are taken from fschain.consensus.p2p, but ports are changed to this value)
    rpc_port: 30334 # Port for network addresses to listen Neo RPC on (addresses are taken from fschain.consensus.rpc, but ports are changed to this value)
