// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: pkg/services/control/ir/types.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Health status of the IR application.
type HealthStatus int32

const (
	// Undefined status, default value.
	HealthStatus_HEALTH_STATUS_UNDEFINED HealthStatus = 0
	// IR application is starting.
	HealthStatus_STARTING HealthStatus = 1
	// IR application is started and serves all services.
	HealthStatus_READY HealthStatus = 2
	// IR application is shutting down.
	HealthStatus_SHUTTING_DOWN HealthStatus = 3
	// Initializing Neo network
	HealthStatus_INITIALIZING_NETWORK HealthStatus = 4
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNDEFINED",
		1: "STARTING",
		2: "READY",
		3: "SHUTTING_DOWN",
		4: "INITIALIZING_NETWORK",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNDEFINED": 0,
		"STARTING":                1,
		"READY":                   2,
		"SHUTTING_DOWN":           3,
		"INITIALIZING_NETWORK":    4,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_services_control_ir_types_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_pkg_services_control_ir_types_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_services_control_ir_types_proto_rawDescGZIP(), []int{0}
}

// Signature of some message.
type Signature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Public key used for signing.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Binary signature.
	Sign          []byte `protobuf:"bytes,2,opt,name=sign,json=signature,proto3" json:"sign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_pkg_services_control_ir_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_control_ir_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_pkg_services_control_ir_types_proto_rawDescGZIP(), []int{0}
}

func (x *Signature) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Signature) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

// Info about transaction.
type TransactionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hash of transaction.
	Hash          []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionInfo) Reset() {
	*x = TransactionInfo{}
	mi := &file_pkg_services_control_ir_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInfo) ProtoMessage() {}

func (x *TransactionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_control_ir_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInfo.ProtoReflect.Descriptor instead.
func (*TransactionInfo) Descriptor() ([]byte, []int) {
	return file_pkg_services_control_ir_types_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionInfo) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

var File_pkg_services_control_ir_types_proto protoreflect.FileDescriptor

const file_pkg_services_control_ir_types_proto_rawDesc = "" +
	"\n" +
	"#pkg/services/control/ir/types.proto\x12\tircontrol\"6\n" +
	"\tSignature\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x17\n" +
	"\x04sign\x18\x02 \x01(\fR\tsignature\"%\n" +
	"\x0fTransactionInfo\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash*q\n" +
	"\fHealthStatus\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNDEFINED\x10\x00\x12\f\n" +
	"\bSTARTING\x10\x01\x12\t\n" +
	"\x05READY\x10\x02\x12\x11\n" +
	"\rSHUTTING_DOWN\x10\x03\x12\x18\n" +
	"\x14INITIALIZING_NETWORK\x10\x04B9Z7github.com/nspcc-dev/neofs-node/pkg/services/ir/controlb\x06proto3"

var (
	file_pkg_services_control_ir_types_proto_rawDescOnce sync.Once
	file_pkg_services_control_ir_types_proto_rawDescData []byte
)

func file_pkg_services_control_ir_types_proto_rawDescGZIP() []byte {
	file_pkg_services_control_ir_types_proto_rawDescOnce.Do(func() {
		file_pkg_services_control_ir_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_services_control_ir_types_proto_rawDesc), len(file_pkg_services_control_ir_types_proto_rawDesc)))
	})
	return file_pkg_services_control_ir_types_proto_rawDescData
}

var file_pkg_services_control_ir_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_services_control_ir_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_services_control_ir_types_proto_goTypes = []any{
	(HealthStatus)(0),       // 0: ircontrol.HealthStatus
	(*Signature)(nil),       // 1: ircontrol.Signature
	(*TransactionInfo)(nil), // 2: ircontrol.TransactionInfo
}
var file_pkg_services_control_ir_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_services_control_ir_types_proto_init() }
func file_pkg_services_control_ir_types_proto_init() {
	if File_pkg_services_control_ir_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_services_control_ir_types_proto_rawDesc), len(file_pkg_services_control_ir_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_services_control_ir_types_proto_goTypes,
		DependencyIndexes: file_pkg_services_control_ir_types_proto_depIdxs,
		EnumInfos:         file_pkg_services_control_ir_types_proto_enumTypes,
		MessageInfos:      file_pkg_services_control_ir_types_proto_msgTypes,
	}.Build()
	File_pkg_services_control_ir_types_proto = out.File
	file_pkg_services_control_ir_types_proto_goTypes = nil
	file_pkg_services_control_ir_types_proto_depIdxs = nil
}
