FROM golang:1.16-alpine as basebuilder
RUN apk add --update make bash

FROM basebuilder as builder
ARG BUILD=now
ARG VERSION=dev
ARG REPO=repository
WORKDIR /src
COPY . /src

RUN make bin/neofs-adm

# Executable image
FROM alpine AS neofs-adm
RUN apk add --no-cache bash

WORKDIR /

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /src/bin/neofs-adm /bin/neofs-adm

CMD ["neofs-adm"]
