name: Add issues to NeoFS Core project

on:
  issues:
    types:
      - opened
      - transferred
      - labeled

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/nspcc-dev/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: triage
