// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/network/transport/metrics/grpc/service.proto

package metrics

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResetSpaceRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetSpaceRequest) Reset()         { *m = ResetSpaceRequest{} }
func (m *ResetSpaceRequest) String() string { return proto.CompactTextString(m) }
func (*ResetSpaceRequest) ProtoMessage()    {}
func (*ResetSpaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdef708412a96383, []int{0}
}
func (m *ResetSpaceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResetSpaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResetSpaceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResetSpaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetSpaceRequest.Merge(m, src)
}
func (m *ResetSpaceRequest) XXX_Size() int {
	return m.Size()
}
func (m *ResetSpaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetSpaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetSpaceRequest proto.InternalMessageInfo

type ResetSpaceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetSpaceResponse) Reset()         { *m = ResetSpaceResponse{} }
func (m *ResetSpaceResponse) String() string { return proto.CompactTextString(m) }
func (*ResetSpaceResponse) ProtoMessage()    {}
func (*ResetSpaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdef708412a96383, []int{1}
}
func (m *ResetSpaceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResetSpaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResetSpaceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResetSpaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetSpaceResponse.Merge(m, src)
}
func (m *ResetSpaceResponse) XXX_Size() int {
	return m.Size()
}
func (m *ResetSpaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetSpaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetSpaceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ResetSpaceRequest)(nil), "metrics.ResetSpaceRequest")
	proto.RegisterType((*ResetSpaceResponse)(nil), "metrics.ResetSpaceResponse")
}

func init() {
	proto.RegisterFile("pkg/network/transport/metrics/grpc/service.proto", fileDescriptor_cdef708412a96383)
}

var fileDescriptor_cdef708412a96383 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xb1, 0x4a, 0xc4, 0x40,
	0x10, 0x86, 0x4d, 0xe3, 0xc1, 0x76, 0xae, 0x56, 0x27, 0x6c, 0x71, 0xfd, 0xed, 0x88, 0xbe, 0xc1,
	0xd9, 0x6a, 0x73, 0x0a, 0x82, 0x5d, 0xb2, 0x19, 0x63, 0x08, 0xd9, 0x59, 0x67, 0x26, 0xf1, 0x55,
	0x7c, 0x24, 0x4b, 0x1f, 0x41, 0xe2, 0x8b, 0x08, 0x49, 0x8a, 0xc0, 0xa5, 0x9d, 0x9f, 0xef, 0x1b,
	0x3e, 0x73, 0x93, 0x9a, 0x0a, 0x22, 0xea, 0x27, 0x71, 0x03, 0xca, 0x79, 0x94, 0x44, 0xac, 0xd0,
	0xa2, 0x72, 0x1d, 0x04, 0x2a, 0x4e, 0x01, 0x04, 0xb9, 0xaf, 0x03, 0xfa, 0xc4, 0xa4, 0x64, 0x37,
	0xf3, 0xb6, 0xbb, 0x34, 0x17, 0x47, 0x14, 0xd4, 0xa7, 0x94, 0x07, 0x3c, 0xe2, 0x47, 0x87, 0xa2,
	0xbb, 0x2b, 0x63, 0x97, 0x47, 0x49, 0x14, 0x05, 0x6f, 0x5f, 0xcc, 0xe6, 0x71, 0xa2, 0xec, 0xc3,
	0x92, 0xba, 0xa7, 0x2e, 0x2a, 0xb2, 0xdd, 0xfa, 0x59, 0xea, 0x4f, 0x8c, 0xdb, 0xeb, 0xd5, 0x6d,
	0x12, 0x1f, 0x9e, 0xbf, 0x07, 0x97, 0xfd, 0x0c, 0x2e, 0xfb, 0x1d, 0x5c, 0xf6, 0xf5, 0xe7, 0xce,
	0x5e, 0x0f, 0x55, 0xad, 0xef, 0x5d, 0xe1, 0x03, 0xb5, 0x10, 0x25, 0x85, 0xb0, 0x2f, 0xb1, 0x87,
	0x88, 0xf4, 0x26, 0xfb, 0x48, 0x25, 0xc2, 0x7a, 0xf0, 0x18, 0x3a, 0x3f, 0x2a, 0xce, 0xc7, 0xd2,
	0xbb, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x26, 0xa6, 0xbe, 0x1d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetricsClient is the client API for Metrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetricsClient interface {
	ResetSpaceCounter(ctx context.Context, in *ResetSpaceRequest, opts ...grpc.CallOption) (*ResetSpaceResponse, error)
}

type metricsClient struct {
	cc *grpc.ClientConn
}

func NewMetricsClient(cc *grpc.ClientConn) MetricsClient {
	return &metricsClient{cc}
}

func (c *metricsClient) ResetSpaceCounter(ctx context.Context, in *ResetSpaceRequest, opts ...grpc.CallOption) (*ResetSpaceResponse, error) {
	out := new(ResetSpaceResponse)
	err := c.cc.Invoke(ctx, "/metrics.Metrics/ResetSpaceCounter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServer is the server API for Metrics service.
type MetricsServer interface {
	ResetSpaceCounter(context.Context, *ResetSpaceRequest) (*ResetSpaceResponse, error)
}

// UnimplementedMetricsServer can be embedded to have forward compatible implementations.
type UnimplementedMetricsServer struct {
}

func (*UnimplementedMetricsServer) ResetSpaceCounter(ctx context.Context, req *ResetSpaceRequest) (*ResetSpaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetSpaceCounter not implemented")
}

func RegisterMetricsServer(s *grpc.Server, srv MetricsServer) {
	s.RegisterService(&_Metrics_serviceDesc, srv)
}

func _Metrics_ResetSpaceCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).ResetSpaceCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrics.Metrics/ResetSpaceCounter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).ResetSpaceCounter(ctx, req.(*ResetSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Metrics_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metrics.Metrics",
	HandlerType: (*MetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResetSpaceCounter",
			Handler:    _Metrics_ResetSpaceCounter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/network/transport/metrics/grpc/service.proto",
}

func (m *ResetSpaceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResetSpaceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResetSpaceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *ResetSpaceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResetSpaceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResetSpaceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func encodeVarintService(dAtA []byte, offset int, v uint64) int {
	offset -= sovService(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ResetSpaceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ResetSpaceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovService(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozService(x uint64) (n int) {
	return sovService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ResetSpaceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResetSpaceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResetSpaceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResetSpaceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResetSpaceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResetSpaceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthService
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupService
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthService
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthService        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowService          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupService = fmt.Errorf("proto: unexpected end of group")
)
